### PR TITLE
Nuke existing test interfaces

### PR DESCRIPTION
**Pull request by smalleni**
# Description

Clean interfaces created by lab automation in RH shared labs.

### CODE REVIEW

**Comment by smalleni** [comment]
@dustinblack PTAL

**Comment by dustinblack** [comment]
Makes sense to me. It the clean-interfaces script always there? I wonder if this task should have an ignore-errors parameter.

**Comment by smalleni** [comment]
Yes, it is always laid down by lab automation. Actually not running this before deploy is causing errors when booting libvirt VMs. Doesn't hurt to add ignore_errors but this is how we do it in jetpack
https://github.com/redhat-performance/jetpack/blob/316d8089906ba04570682bc1aa2c11ca634965db/prepare_undercloud.yml#L32-L35

**Comment by mkarg75** [comment]
I never had to use it, but I don't see it doing any harm, so it looks good from my point of view.

**Pull request merged**
